//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvl.Java.DebugInterface.Client.DebugProtocol {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DebugProtocol.IDebugProtocolService", CallbackContract=typeof(Tvl.Java.DebugInterface.Client.DebugProtocol.IDebugProtocolServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDebugProtocolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/Attach", ReplyAction="http://tempuri.org/IDebugProtocolService/AttachResponse")]
        Tvl.Java.DebugInterface.Types.Error Attach();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetVersion", ReplyAction="http://tempuri.org/IDebugProtocolService/GetVersionResponse")]
        Tvl.Java.DebugInterface.Types.Error GetVersion(out string description, out int majorVersion, out int minorVersion, out string vmVersion, out string vmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetClassesBySignature", ReplyAction="http://tempuri.org/IDebugProtocolService/GetClassesBySignatureResponse")]
        Tvl.Java.DebugInterface.Types.Error GetClassesBySignature(out Tvl.Java.DebugInterface.Types.ReferenceTypeData[] classes, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetAllClasses", ReplyAction="http://tempuri.org/IDebugProtocolService/GetAllClassesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetAllClasses(out Tvl.Java.DebugInterface.Types.ReferenceTypeData[] classes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetAllThreads", ReplyAction="http://tempuri.org/IDebugProtocolService/GetAllThreadsResponse")]
        Tvl.Java.DebugInterface.Types.Error GetAllThreads(out Tvl.Java.DebugInterface.Types.ThreadId[] threads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetTopLevelThreadGroups", ReplyAction="http://tempuri.org/IDebugProtocolService/GetTopLevelThreadGroupsResponse")]
        Tvl.Java.DebugInterface.Types.Error GetTopLevelThreadGroups(out Tvl.Java.DebugInterface.Types.ThreadGroupId[] groups);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/Dispose", ReplyAction="http://tempuri.org/IDebugProtocolService/DisposeResponse")]
        Tvl.Java.DebugInterface.Types.Error Dispose();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/Suspend", ReplyAction="http://tempuri.org/IDebugProtocolService/SuspendResponse")]
        Tvl.Java.DebugInterface.Types.Error Suspend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/Resume", ReplyAction="http://tempuri.org/IDebugProtocolService/ResumeResponse")]
        Tvl.Java.DebugInterface.Types.Error Resume();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/Exit", ReplyAction="http://tempuri.org/IDebugProtocolService/ExitResponse")]
        Tvl.Java.DebugInterface.Types.Error Exit(int exitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/CreateString", ReplyAction="http://tempuri.org/IDebugProtocolService/CreateStringResponse")]
        Tvl.Java.DebugInterface.Types.Error CreateString(out Tvl.Java.DebugInterface.Types.StringId stringObject, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetCapabilities", ReplyAction="http://tempuri.org/IDebugProtocolService/GetCapabilitiesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetCapabilities(out Tvl.Java.DebugInterface.Types.Capabilities capabilities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetClassPaths", ReplyAction="http://tempuri.org/IDebugProtocolService/GetClassPathsResponse")]
        Tvl.Java.DebugInterface.Types.Error GetClassPaths(out string baseDirectory, out string[] classPaths, out string[] bootClassPaths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/DisposeObjects", ReplyAction="http://tempuri.org/IDebugProtocolService/DisposeObjectsResponse")]
        Tvl.Java.DebugInterface.Types.Error DisposeObjects(Tvl.Java.DebugInterface.Types.ObjectReferenceCountData[] requests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/HoldEvents", ReplyAction="http://tempuri.org/IDebugProtocolService/HoldEventsResponse")]
        Tvl.Java.DebugInterface.Types.Error HoldEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/ReleaseEvents", ReplyAction="http://tempuri.org/IDebugProtocolService/ReleaseEventsResponse")]
        Tvl.Java.DebugInterface.Types.Error ReleaseEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/RedefineClasses", ReplyAction="http://tempuri.org/IDebugProtocolService/RedefineClassesResponse")]
        Tvl.Java.DebugInterface.Types.Error RedefineClasses(Tvl.Java.DebugInterface.Types.ClassDefinitionData[] definitions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/SetDefaultStratum", ReplyAction="http://tempuri.org/IDebugProtocolService/SetDefaultStratumResponse")]
        Tvl.Java.DebugInterface.Types.Error SetDefaultStratum(string stratumId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetSignature", ReplyAction="http://tempuri.org/IDebugProtocolService/GetSignatureResponse")]
        Tvl.Java.DebugInterface.Types.Error GetSignature(out string signature, out string genericSignature, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetClassLoader", ReplyAction="http://tempuri.org/IDebugProtocolService/GetClassLoaderResponse")]
        Tvl.Java.DebugInterface.Types.Error GetClassLoader(out Tvl.Java.DebugInterface.Types.ClassLoaderId classLoader, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetModifiers", ReplyAction="http://tempuri.org/IDebugProtocolService/GetModifiersResponse")]
        Tvl.Java.DebugInterface.Types.Error GetModifiers(out Tvl.Java.DebugInterface.Types.AccessModifiers modifiers, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetFields", ReplyAction="http://tempuri.org/IDebugProtocolService/GetFieldsResponse")]
        Tvl.Java.DebugInterface.Types.Error GetFields(out Tvl.Java.DebugInterface.Types.DeclaredFieldData[] fields, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetMethods", ReplyAction="http://tempuri.org/IDebugProtocolService/GetMethodsResponse")]
        Tvl.Java.DebugInterface.Types.Error GetMethods(out Tvl.Java.DebugInterface.Types.DeclaredMethodData[] methods, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetReferenceTypeValues", ReplyAction="http://tempuri.org/IDebugProtocolService/GetReferenceTypeValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetReferenceTypeValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.FieldId[] fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetSourceFile", ReplyAction="http://tempuri.org/IDebugProtocolService/GetSourceFileResponse")]
        Tvl.Java.DebugInterface.Types.Error GetSourceFile(out string sourceFile, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetNestedTypes", ReplyAction="http://tempuri.org/IDebugProtocolService/GetNestedTypesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetNestedTypes(out Tvl.Java.DebugInterface.Types.TaggedReferenceTypeId[] classes, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetReferenceTypeStatus", ReplyAction="http://tempuri.org/IDebugProtocolService/GetReferenceTypeStatusResponse")]
        Tvl.Java.DebugInterface.Types.Error GetReferenceTypeStatus(out Tvl.Java.DebugInterface.Types.ClassStatus status, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetInterfaces", ReplyAction="http://tempuri.org/IDebugProtocolService/GetInterfacesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetInterfaces(out Tvl.Java.DebugInterface.Types.InterfaceId[] interfaces, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetClassObject", ReplyAction="http://tempuri.org/IDebugProtocolService/GetClassObjectResponse")]
        Tvl.Java.DebugInterface.Types.Error GetClassObject(out Tvl.Java.DebugInterface.Types.ClassObjectId classObject, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetSourceDebugExtension", ReplyAction="http://tempuri.org/IDebugProtocolService/GetSourceDebugExtensionResponse")]
        Tvl.Java.DebugInterface.Types.Error GetSourceDebugExtension(out string extension, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetInstances", ReplyAction="http://tempuri.org/IDebugProtocolService/GetInstancesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetInstances(out Tvl.Java.DebugInterface.Types.TaggedObjectId[] instances, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, int maxInstances);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetClassFileVersion", ReplyAction="http://tempuri.org/IDebugProtocolService/GetClassFileVersionResponse")]
        Tvl.Java.DebugInterface.Types.Error GetClassFileVersion(out int majorVersion, out int minorVersion, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetConstantPool", ReplyAction="http://tempuri.org/IDebugProtocolService/GetConstantPoolResponse")]
        Tvl.Java.DebugInterface.Types.Error GetConstantPool(out int constantPoolCount, out byte[] data, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetSuperclass", ReplyAction="http://tempuri.org/IDebugProtocolService/GetSuperclassResponse")]
        Tvl.Java.DebugInterface.Types.Error GetSuperclass(out Tvl.Java.DebugInterface.Types.ClassId superclass, Tvl.Java.DebugInterface.Types.ClassId @class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/SetClassValues", ReplyAction="http://tempuri.org/IDebugProtocolService/SetClassValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error SetClassValues(Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.FieldId[] fields, Tvl.Java.DebugInterface.Types.Value[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/InvokeClassMethod", ReplyAction="http://tempuri.org/IDebugProtocolService/InvokeClassMethodResponse")]
        Tvl.Java.DebugInterface.Types.Error InvokeClassMethod(out Tvl.Java.DebugInterface.Types.Value returnValue, out Tvl.Java.DebugInterface.Types.TaggedObjectId thrownException, Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.MethodId method, Tvl.Java.DebugInterface.Types.InvokeOptions options, Tvl.Java.DebugInterface.Types.Value[] arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/CreateClassInstance", ReplyAction="http://tempuri.org/IDebugProtocolService/CreateClassInstanceResponse")]
        Tvl.Java.DebugInterface.Types.Error CreateClassInstance(out Tvl.Java.DebugInterface.Types.TaggedObjectId newObject, out Tvl.Java.DebugInterface.Types.TaggedObjectId thrownException, Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.MethodId method, Tvl.Java.DebugInterface.Types.InvokeOptions options, Tvl.Java.DebugInterface.Types.Value[] arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/CreateArrayInstance", ReplyAction="http://tempuri.org/IDebugProtocolService/CreateArrayInstanceResponse")]
        Tvl.Java.DebugInterface.Types.Error CreateArrayInstance(out Tvl.Java.DebugInterface.Types.TaggedObjectId newArray, Tvl.Java.DebugInterface.Types.ArrayTypeId arrayType, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetMethodExceptionTable", ReplyAction="http://tempuri.org/IDebugProtocolService/GetMethodExceptionTableResponse")]
        Tvl.Java.DebugInterface.Types.Error GetMethodExceptionTable(out Tvl.Java.DebugInterface.Types.Loader.ExceptionTableEntry[] entries, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetMethodLineTable", ReplyAction="http://tempuri.org/IDebugProtocolService/GetMethodLineTableResponse")]
        Tvl.Java.DebugInterface.Types.Error GetMethodLineTable(out long start, out long end, out Tvl.Java.DebugInterface.Types.LineNumberData[] lines, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetMethodVariableTable", ReplyAction="http://tempuri.org/IDebugProtocolService/GetMethodVariableTableResponse")]
        Tvl.Java.DebugInterface.Types.Error GetMethodVariableTable(out Tvl.Java.DebugInterface.Types.VariableData[] slots, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetMethodBytecodes", ReplyAction="http://tempuri.org/IDebugProtocolService/GetMethodBytecodesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetMethodBytecodes(out byte[] bytecode, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetMethodIsObsolete", ReplyAction="http://tempuri.org/IDebugProtocolService/GetMethodIsObsoleteResponse")]
        Tvl.Java.DebugInterface.Types.Error GetMethodIsObsolete(out bool result, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetObjectReferenceType", ReplyAction="http://tempuri.org/IDebugProtocolService/GetObjectReferenceTypeResponse")]
        Tvl.Java.DebugInterface.Types.Error GetObjectReferenceType(out Tvl.Java.DebugInterface.Types.TypeTag typeTag, out Tvl.Java.DebugInterface.Types.ReferenceTypeId typeId, Tvl.Java.DebugInterface.Types.ObjectId @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetObjectValues", ReplyAction="http://tempuri.org/IDebugProtocolService/GetObjectValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetObjectValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ObjectId @object, Tvl.Java.DebugInterface.Types.FieldId[] fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/SetObjectValues", ReplyAction="http://tempuri.org/IDebugProtocolService/SetObjectValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error SetObjectValues(Tvl.Java.DebugInterface.Types.ObjectId @object, Tvl.Java.DebugInterface.Types.FieldId[] fields, Tvl.Java.DebugInterface.Types.Value[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetObjectMonitorInfo", ReplyAction="http://tempuri.org/IDebugProtocolService/GetObjectMonitorInfoResponse")]
        Tvl.Java.DebugInterface.Types.Error GetObjectMonitorInfo(out Tvl.Java.DebugInterface.Types.ThreadId owner, out int entryCount, out Tvl.Java.DebugInterface.Types.ThreadId[] waiters, Tvl.Java.DebugInterface.Types.ObjectId @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/InvokeObjectMethod", ReplyAction="http://tempuri.org/IDebugProtocolService/InvokeObjectMethodResponse")]
        Tvl.Java.DebugInterface.Types.Error InvokeObjectMethod(out Tvl.Java.DebugInterface.Types.Value returnValue, out Tvl.Java.DebugInterface.Types.TaggedObjectId thrownException, Tvl.Java.DebugInterface.Types.ObjectId @object, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.MethodId method, Tvl.Java.DebugInterface.Types.InvokeOptions options, Tvl.Java.DebugInterface.Types.Value[] arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/DisableObjectCollection", ReplyAction="http://tempuri.org/IDebugProtocolService/DisableObjectCollectionResponse")]
        Tvl.Java.DebugInterface.Types.Error DisableObjectCollection(Tvl.Java.DebugInterface.Types.ObjectId @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/EnableObjectCollection", ReplyAction="http://tempuri.org/IDebugProtocolService/EnableObjectCollectionResponse")]
        Tvl.Java.DebugInterface.Types.Error EnableObjectCollection(Tvl.Java.DebugInterface.Types.ObjectId @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetIsObjectCollected", ReplyAction="http://tempuri.org/IDebugProtocolService/GetIsObjectCollectedResponse")]
        Tvl.Java.DebugInterface.Types.Error GetIsObjectCollected(out bool result, Tvl.Java.DebugInterface.Types.ObjectId @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetStringValue", ReplyAction="http://tempuri.org/IDebugProtocolService/GetStringValueResponse")]
        Tvl.Java.DebugInterface.Types.Error GetStringValue(out string stringValue, Tvl.Java.DebugInterface.Types.ObjectId stringObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadName", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadNameResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadName(out string name, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/SuspendThread", ReplyAction="http://tempuri.org/IDebugProtocolService/SuspendThreadResponse")]
        Tvl.Java.DebugInterface.Types.Error SuspendThread(Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/ResumeThread", ReplyAction="http://tempuri.org/IDebugProtocolService/ResumeThreadResponse")]
        Tvl.Java.DebugInterface.Types.Error ResumeThread(Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadStatus", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadStatusResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadStatus(out Tvl.Java.DebugInterface.Types.ThreadStatus threadStatus, out Tvl.Java.DebugInterface.Types.SuspendStatus suspendStatus, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadGroup", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadGroupResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadGroup(out Tvl.Java.DebugInterface.Types.ThreadGroupId threadGroup, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadFrames", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadFramesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadFrames(out Tvl.Java.DebugInterface.Types.FrameLocationData[] frames, Tvl.Java.DebugInterface.Types.ThreadId thread, int startFrame, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadFrameCount", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadFrameCountResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadFrameCount(out int frameCount, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadOwnedMonitors", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadOwnedMonitorsResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadOwnedMonitors(out Tvl.Java.DebugInterface.Types.TaggedObjectId[] monitors, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadCurrentContendedMonitor", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadCurrentContendedMonitorResponse" +
            "")]
        Tvl.Java.DebugInterface.Types.Error GetThreadCurrentContendedMonitor(out Tvl.Java.DebugInterface.Types.TaggedObjectId monitor, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/StopThread", ReplyAction="http://tempuri.org/IDebugProtocolService/StopThreadResponse")]
        Tvl.Java.DebugInterface.Types.Error StopThread(Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.ObjectId throwable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/InterruptThread", ReplyAction="http://tempuri.org/IDebugProtocolService/InterruptThreadResponse")]
        Tvl.Java.DebugInterface.Types.Error InterruptThread(Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadSuspendCount", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadSuspendCountResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadSuspendCount(out int suspendCount, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadGroupName", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadGroupNameResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadGroupName(out string groupName, Tvl.Java.DebugInterface.Types.ThreadGroupId group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadGroupParent", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadGroupParentResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadGroupParent(out Tvl.Java.DebugInterface.Types.ThreadGroupId parentGroup, Tvl.Java.DebugInterface.Types.ThreadGroupId group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThreadGroupChildren", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThreadGroupChildrenResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThreadGroupChildren(out Tvl.Java.DebugInterface.Types.ThreadId[] childThreads, out Tvl.Java.DebugInterface.Types.ThreadGroupId[] childGroups, Tvl.Java.DebugInterface.Types.ThreadGroupId group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetArrayLength", ReplyAction="http://tempuri.org/IDebugProtocolService/GetArrayLengthResponse")]
        Tvl.Java.DebugInterface.Types.Error GetArrayLength(out int arrayLength, Tvl.Java.DebugInterface.Types.ArrayId arrayObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetArrayValues", ReplyAction="http://tempuri.org/IDebugProtocolService/GetArrayValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetArrayValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ArrayId arrayObject, int firstIndex, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/SetArrayValues", ReplyAction="http://tempuri.org/IDebugProtocolService/SetArrayValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error SetArrayValues(Tvl.Java.DebugInterface.Types.ArrayId arrayObject, int firstIndex, Tvl.Java.DebugInterface.Types.Value[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetClassLoaderVisibleClasses", ReplyAction="http://tempuri.org/IDebugProtocolService/GetClassLoaderVisibleClassesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetClassLoaderVisibleClasses(out Tvl.Java.DebugInterface.Types.TaggedReferenceTypeId[] classes, Tvl.Java.DebugInterface.Types.ClassLoaderId classLoaderObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/SetEvent", ReplyAction="http://tempuri.org/IDebugProtocolService/SetEventResponse")]
        Tvl.Java.DebugInterface.Types.Error SetEvent(out Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.EventKind eventKind, Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.EventRequestModifier[] modifiers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/ClearEvent", ReplyAction="http://tempuri.org/IDebugProtocolService/ClearEventResponse")]
        Tvl.Java.DebugInterface.Types.Error ClearEvent(Tvl.Java.DebugInterface.Types.EventKind eventKind, Tvl.Java.DebugInterface.Types.RequestId requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/ClearAllBreakpoints", ReplyAction="http://tempuri.org/IDebugProtocolService/ClearAllBreakpointsResponse")]
        Tvl.Java.DebugInterface.Types.Error ClearAllBreakpoints();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetValues", ReplyAction="http://tempuri.org/IDebugProtocolService/GetValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error GetValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame, int[] slots);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/SetValues", ReplyAction="http://tempuri.org/IDebugProtocolService/SetValuesResponse")]
        Tvl.Java.DebugInterface.Types.Error SetValues(Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame, int[] slots, Tvl.Java.DebugInterface.Types.Value[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetThisObject", ReplyAction="http://tempuri.org/IDebugProtocolService/GetThisObjectResponse")]
        Tvl.Java.DebugInterface.Types.Error GetThisObject(out Tvl.Java.DebugInterface.Types.TaggedObjectId thisObject, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/PopFrames", ReplyAction="http://tempuri.org/IDebugProtocolService/PopFramesResponse")]
        Tvl.Java.DebugInterface.Types.Error PopFrames(Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebugProtocolService/GetReflectedType", ReplyAction="http://tempuri.org/IDebugProtocolService/GetReflectedTypeResponse")]
        Tvl.Java.DebugInterface.Types.Error GetReflectedType(out Tvl.Java.DebugInterface.Types.TypeTag typeTag, out Tvl.Java.DebugInterface.Types.ReferenceTypeId typeId, Tvl.Java.DebugInterface.Types.ClassObjectId classObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDebugProtocolServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/VirtualMachineStart")]
        void VirtualMachineStart(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/SingleStep")]
        void SingleStep(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.Location location);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/Breakpoint")]
        void Breakpoint(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.Location location);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/MethodEntry")]
        void MethodEntry(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.Location location);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/MethodExit")]
        void MethodExit(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.Location location, Tvl.Java.DebugInterface.Types.Value returnValue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/MonitorContendedEnter")]
        void MonitorContendedEnter(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.TaggedObjectId @object, Tvl.Java.DebugInterface.Types.Location location);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/MonitorContendedEntered")]
        void MonitorContendedEntered(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.TaggedObjectId @object, Tvl.Java.DebugInterface.Types.Location location);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/MonitorContendedWait")]
        void MonitorContendedWait(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.TaggedObjectId @object, Tvl.Java.DebugInterface.Types.Location location, System.TimeSpan timeout);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/MonitorContendedWaited")]
        void MonitorContendedWaited(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.TaggedObjectId @object, Tvl.Java.DebugInterface.Types.Location location, bool timedOut);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/Exception")]
        void Exception(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.Location location, [System.ServiceModel.MessageParameterAttribute(Name="exception")] Tvl.Java.DebugInterface.Types.TaggedObjectId exception1, Tvl.Java.DebugInterface.Types.Location catchLocation);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/ThreadStart")]
        void ThreadStart(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/ThreadDeath")]
        void ThreadDeath(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/ClassPrepare")]
        void ClassPrepare(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.TypeTag typeTag, Tvl.Java.DebugInterface.Types.ReferenceTypeId typeId, string signature, Tvl.Java.DebugInterface.Types.ClassStatus status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/ClassUnload")]
        void ClassUnload(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, string signature);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/FieldAccess")]
        void FieldAccess(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.Location location, Tvl.Java.DebugInterface.Types.TypeTag typeTag, Tvl.Java.DebugInterface.Types.ReferenceTypeId typeId, Tvl.Java.DebugInterface.Types.FieldId field, Tvl.Java.DebugInterface.Types.TaggedObjectId @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/FieldModification")]
        void FieldModification(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.Location location, Tvl.Java.DebugInterface.Types.TypeTag typeTag, Tvl.Java.DebugInterface.Types.ReferenceTypeId typeId, Tvl.Java.DebugInterface.Types.FieldId field, Tvl.Java.DebugInterface.Types.TaggedObjectId @object, Tvl.Java.DebugInterface.Types.Value newValue);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDebugProtocolService/VirtualMachineDeath")]
        void VirtualMachineDeath(Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.RequestId requestId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDebugProtocolServiceChannel : Tvl.Java.DebugInterface.Client.DebugProtocol.IDebugProtocolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DebugProtocolServiceClient : System.ServiceModel.DuplexClientBase<Tvl.Java.DebugInterface.Client.DebugProtocol.IDebugProtocolService>, Tvl.Java.DebugInterface.Client.DebugProtocol.IDebugProtocolService {
        
        public DebugProtocolServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DebugProtocolServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DebugProtocolServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DebugProtocolServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DebugProtocolServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Tvl.Java.DebugInterface.Types.Error Attach() {
            return base.Channel.Attach();
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetVersion(out string description, out int majorVersion, out int minorVersion, out string vmVersion, out string vmName) {
            return base.Channel.GetVersion(out description, out majorVersion, out minorVersion, out vmVersion, out vmName);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetClassesBySignature(out Tvl.Java.DebugInterface.Types.ReferenceTypeData[] classes, string signature) {
            return base.Channel.GetClassesBySignature(out classes, signature);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetAllClasses(out Tvl.Java.DebugInterface.Types.ReferenceTypeData[] classes) {
            return base.Channel.GetAllClasses(out classes);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetAllThreads(out Tvl.Java.DebugInterface.Types.ThreadId[] threads) {
            return base.Channel.GetAllThreads(out threads);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetTopLevelThreadGroups(out Tvl.Java.DebugInterface.Types.ThreadGroupId[] groups) {
            return base.Channel.GetTopLevelThreadGroups(out groups);
        }
        
        public Tvl.Java.DebugInterface.Types.Error Dispose() {
            return base.Channel.Dispose();
        }
        
        public Tvl.Java.DebugInterface.Types.Error Suspend() {
            return base.Channel.Suspend();
        }
        
        public Tvl.Java.DebugInterface.Types.Error Resume() {
            return base.Channel.Resume();
        }
        
        public Tvl.Java.DebugInterface.Types.Error Exit(int exitCode) {
            return base.Channel.Exit(exitCode);
        }
        
        public Tvl.Java.DebugInterface.Types.Error CreateString(out Tvl.Java.DebugInterface.Types.StringId stringObject, string value) {
            return base.Channel.CreateString(out stringObject, value);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetCapabilities(out Tvl.Java.DebugInterface.Types.Capabilities capabilities) {
            return base.Channel.GetCapabilities(out capabilities);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetClassPaths(out string baseDirectory, out string[] classPaths, out string[] bootClassPaths) {
            return base.Channel.GetClassPaths(out baseDirectory, out classPaths, out bootClassPaths);
        }
        
        public Tvl.Java.DebugInterface.Types.Error DisposeObjects(Tvl.Java.DebugInterface.Types.ObjectReferenceCountData[] requests) {
            return base.Channel.DisposeObjects(requests);
        }
        
        public Tvl.Java.DebugInterface.Types.Error HoldEvents() {
            return base.Channel.HoldEvents();
        }
        
        public Tvl.Java.DebugInterface.Types.Error ReleaseEvents() {
            return base.Channel.ReleaseEvents();
        }
        
        public Tvl.Java.DebugInterface.Types.Error RedefineClasses(Tvl.Java.DebugInterface.Types.ClassDefinitionData[] definitions) {
            return base.Channel.RedefineClasses(definitions);
        }
        
        public Tvl.Java.DebugInterface.Types.Error SetDefaultStratum(string stratumId) {
            return base.Channel.SetDefaultStratum(stratumId);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetSignature(out string signature, out string genericSignature, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetSignature(out signature, out genericSignature, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetClassLoader(out Tvl.Java.DebugInterface.Types.ClassLoaderId classLoader, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetClassLoader(out classLoader, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetModifiers(out Tvl.Java.DebugInterface.Types.AccessModifiers modifiers, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetModifiers(out modifiers, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetFields(out Tvl.Java.DebugInterface.Types.DeclaredFieldData[] fields, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetFields(out fields, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetMethods(out Tvl.Java.DebugInterface.Types.DeclaredMethodData[] methods, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetMethods(out methods, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetReferenceTypeValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.FieldId[] fields) {
            return base.Channel.GetReferenceTypeValues(out values, referenceType, fields);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetSourceFile(out string sourceFile, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetSourceFile(out sourceFile, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetNestedTypes(out Tvl.Java.DebugInterface.Types.TaggedReferenceTypeId[] classes, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetNestedTypes(out classes, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetReferenceTypeStatus(out Tvl.Java.DebugInterface.Types.ClassStatus status, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetReferenceTypeStatus(out status, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetInterfaces(out Tvl.Java.DebugInterface.Types.InterfaceId[] interfaces, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetInterfaces(out interfaces, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetClassObject(out Tvl.Java.DebugInterface.Types.ClassObjectId classObject, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetClassObject(out classObject, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetSourceDebugExtension(out string extension, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetSourceDebugExtension(out extension, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetInstances(out Tvl.Java.DebugInterface.Types.TaggedObjectId[] instances, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, int maxInstances) {
            return base.Channel.GetInstances(out instances, referenceType, maxInstances);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetClassFileVersion(out int majorVersion, out int minorVersion, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetClassFileVersion(out majorVersion, out minorVersion, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetConstantPool(out int constantPoolCount, out byte[] data, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType) {
            return base.Channel.GetConstantPool(out constantPoolCount, out data, referenceType);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetSuperclass(out Tvl.Java.DebugInterface.Types.ClassId superclass, Tvl.Java.DebugInterface.Types.ClassId @class) {
            return base.Channel.GetSuperclass(out superclass, @class);
        }
        
        public Tvl.Java.DebugInterface.Types.Error SetClassValues(Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.FieldId[] fields, Tvl.Java.DebugInterface.Types.Value[] values) {
            return base.Channel.SetClassValues(@class, fields, values);
        }
        
        public Tvl.Java.DebugInterface.Types.Error InvokeClassMethod(out Tvl.Java.DebugInterface.Types.Value returnValue, out Tvl.Java.DebugInterface.Types.TaggedObjectId thrownException, Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.MethodId method, Tvl.Java.DebugInterface.Types.InvokeOptions options, Tvl.Java.DebugInterface.Types.Value[] arguments) {
            return base.Channel.InvokeClassMethod(out returnValue, out thrownException, @class, thread, method, options, arguments);
        }
        
        public Tvl.Java.DebugInterface.Types.Error CreateClassInstance(out Tvl.Java.DebugInterface.Types.TaggedObjectId newObject, out Tvl.Java.DebugInterface.Types.TaggedObjectId thrownException, Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.MethodId method, Tvl.Java.DebugInterface.Types.InvokeOptions options, Tvl.Java.DebugInterface.Types.Value[] arguments) {
            return base.Channel.CreateClassInstance(out newObject, out thrownException, @class, thread, method, options, arguments);
        }
        
        public Tvl.Java.DebugInterface.Types.Error CreateArrayInstance(out Tvl.Java.DebugInterface.Types.TaggedObjectId newArray, Tvl.Java.DebugInterface.Types.ArrayTypeId arrayType, int length) {
            return base.Channel.CreateArrayInstance(out newArray, arrayType, length);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetMethodExceptionTable(out Tvl.Java.DebugInterface.Types.Loader.ExceptionTableEntry[] entries, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method) {
            return base.Channel.GetMethodExceptionTable(out entries, referenceType, method);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetMethodLineTable(out long start, out long end, out Tvl.Java.DebugInterface.Types.LineNumberData[] lines, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method) {
            return base.Channel.GetMethodLineTable(out start, out end, out lines, referenceType, method);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetMethodVariableTable(out Tvl.Java.DebugInterface.Types.VariableData[] slots, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method) {
            return base.Channel.GetMethodVariableTable(out slots, referenceType, method);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetMethodBytecodes(out byte[] bytecode, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method) {
            return base.Channel.GetMethodBytecodes(out bytecode, referenceType, method);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetMethodIsObsolete(out bool result, Tvl.Java.DebugInterface.Types.ReferenceTypeId referenceType, Tvl.Java.DebugInterface.Types.MethodId method) {
            return base.Channel.GetMethodIsObsolete(out result, referenceType, method);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetObjectReferenceType(out Tvl.Java.DebugInterface.Types.TypeTag typeTag, out Tvl.Java.DebugInterface.Types.ReferenceTypeId typeId, Tvl.Java.DebugInterface.Types.ObjectId @object) {
            return base.Channel.GetObjectReferenceType(out typeTag, out typeId, @object);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetObjectValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ObjectId @object, Tvl.Java.DebugInterface.Types.FieldId[] fields) {
            return base.Channel.GetObjectValues(out values, @object, fields);
        }
        
        public Tvl.Java.DebugInterface.Types.Error SetObjectValues(Tvl.Java.DebugInterface.Types.ObjectId @object, Tvl.Java.DebugInterface.Types.FieldId[] fields, Tvl.Java.DebugInterface.Types.Value[] values) {
            return base.Channel.SetObjectValues(@object, fields, values);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetObjectMonitorInfo(out Tvl.Java.DebugInterface.Types.ThreadId owner, out int entryCount, out Tvl.Java.DebugInterface.Types.ThreadId[] waiters, Tvl.Java.DebugInterface.Types.ObjectId @object) {
            return base.Channel.GetObjectMonitorInfo(out owner, out entryCount, out waiters, @object);
        }
        
        public Tvl.Java.DebugInterface.Types.Error InvokeObjectMethod(out Tvl.Java.DebugInterface.Types.Value returnValue, out Tvl.Java.DebugInterface.Types.TaggedObjectId thrownException, Tvl.Java.DebugInterface.Types.ObjectId @object, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.ClassId @class, Tvl.Java.DebugInterface.Types.MethodId method, Tvl.Java.DebugInterface.Types.InvokeOptions options, Tvl.Java.DebugInterface.Types.Value[] arguments) {
            return base.Channel.InvokeObjectMethod(out returnValue, out thrownException, @object, thread, @class, method, options, arguments);
        }
        
        public Tvl.Java.DebugInterface.Types.Error DisableObjectCollection(Tvl.Java.DebugInterface.Types.ObjectId @object) {
            return base.Channel.DisableObjectCollection(@object);
        }
        
        public Tvl.Java.DebugInterface.Types.Error EnableObjectCollection(Tvl.Java.DebugInterface.Types.ObjectId @object) {
            return base.Channel.EnableObjectCollection(@object);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetIsObjectCollected(out bool result, Tvl.Java.DebugInterface.Types.ObjectId @object) {
            return base.Channel.GetIsObjectCollected(out result, @object);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetStringValue(out string stringValue, Tvl.Java.DebugInterface.Types.ObjectId stringObject) {
            return base.Channel.GetStringValue(out stringValue, stringObject);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadName(out string name, Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.GetThreadName(out name, thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error SuspendThread(Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.SuspendThread(thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error ResumeThread(Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.ResumeThread(thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadStatus(out Tvl.Java.DebugInterface.Types.ThreadStatus threadStatus, out Tvl.Java.DebugInterface.Types.SuspendStatus suspendStatus, Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.GetThreadStatus(out threadStatus, out suspendStatus, thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadGroup(out Tvl.Java.DebugInterface.Types.ThreadGroupId threadGroup, Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.GetThreadGroup(out threadGroup, thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadFrames(out Tvl.Java.DebugInterface.Types.FrameLocationData[] frames, Tvl.Java.DebugInterface.Types.ThreadId thread, int startFrame, int length) {
            return base.Channel.GetThreadFrames(out frames, thread, startFrame, length);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadFrameCount(out int frameCount, Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.GetThreadFrameCount(out frameCount, thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadOwnedMonitors(out Tvl.Java.DebugInterface.Types.TaggedObjectId[] monitors, Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.GetThreadOwnedMonitors(out monitors, thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadCurrentContendedMonitor(out Tvl.Java.DebugInterface.Types.TaggedObjectId monitor, Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.GetThreadCurrentContendedMonitor(out monitor, thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error StopThread(Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.ObjectId throwable) {
            return base.Channel.StopThread(thread, throwable);
        }
        
        public Tvl.Java.DebugInterface.Types.Error InterruptThread(Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.InterruptThread(thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadSuspendCount(out int suspendCount, Tvl.Java.DebugInterface.Types.ThreadId thread) {
            return base.Channel.GetThreadSuspendCount(out suspendCount, thread);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadGroupName(out string groupName, Tvl.Java.DebugInterface.Types.ThreadGroupId group) {
            return base.Channel.GetThreadGroupName(out groupName, group);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadGroupParent(out Tvl.Java.DebugInterface.Types.ThreadGroupId parentGroup, Tvl.Java.DebugInterface.Types.ThreadGroupId group) {
            return base.Channel.GetThreadGroupParent(out parentGroup, group);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThreadGroupChildren(out Tvl.Java.DebugInterface.Types.ThreadId[] childThreads, out Tvl.Java.DebugInterface.Types.ThreadGroupId[] childGroups, Tvl.Java.DebugInterface.Types.ThreadGroupId group) {
            return base.Channel.GetThreadGroupChildren(out childThreads, out childGroups, group);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetArrayLength(out int arrayLength, Tvl.Java.DebugInterface.Types.ArrayId arrayObject) {
            return base.Channel.GetArrayLength(out arrayLength, arrayObject);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetArrayValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ArrayId arrayObject, int firstIndex, int length) {
            return base.Channel.GetArrayValues(out values, arrayObject, firstIndex, length);
        }
        
        public Tvl.Java.DebugInterface.Types.Error SetArrayValues(Tvl.Java.DebugInterface.Types.ArrayId arrayObject, int firstIndex, Tvl.Java.DebugInterface.Types.Value[] values) {
            return base.Channel.SetArrayValues(arrayObject, firstIndex, values);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetClassLoaderVisibleClasses(out Tvl.Java.DebugInterface.Types.TaggedReferenceTypeId[] classes, Tvl.Java.DebugInterface.Types.ClassLoaderId classLoaderObject) {
            return base.Channel.GetClassLoaderVisibleClasses(out classes, classLoaderObject);
        }
        
        public Tvl.Java.DebugInterface.Types.Error SetEvent(out Tvl.Java.DebugInterface.Types.RequestId requestId, Tvl.Java.DebugInterface.Types.EventKind eventKind, Tvl.Java.DebugInterface.Types.SuspendPolicy suspendPolicy, Tvl.Java.DebugInterface.Types.EventRequestModifier[] modifiers) {
            return base.Channel.SetEvent(out requestId, eventKind, suspendPolicy, modifiers);
        }
        
        public Tvl.Java.DebugInterface.Types.Error ClearEvent(Tvl.Java.DebugInterface.Types.EventKind eventKind, Tvl.Java.DebugInterface.Types.RequestId requestId) {
            return base.Channel.ClearEvent(eventKind, requestId);
        }
        
        public Tvl.Java.DebugInterface.Types.Error ClearAllBreakpoints() {
            return base.Channel.ClearAllBreakpoints();
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetValues(out Tvl.Java.DebugInterface.Types.Value[] values, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame, int[] slots) {
            return base.Channel.GetValues(out values, thread, frame, slots);
        }
        
        public Tvl.Java.DebugInterface.Types.Error SetValues(Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame, int[] slots, Tvl.Java.DebugInterface.Types.Value[] values) {
            return base.Channel.SetValues(thread, frame, slots, values);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetThisObject(out Tvl.Java.DebugInterface.Types.TaggedObjectId thisObject, Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame) {
            return base.Channel.GetThisObject(out thisObject, thread, frame);
        }
        
        public Tvl.Java.DebugInterface.Types.Error PopFrames(Tvl.Java.DebugInterface.Types.ThreadId thread, Tvl.Java.DebugInterface.Types.FrameId frame) {
            return base.Channel.PopFrames(thread, frame);
        }
        
        public Tvl.Java.DebugInterface.Types.Error GetReflectedType(out Tvl.Java.DebugInterface.Types.TypeTag typeTag, out Tvl.Java.DebugInterface.Types.ReferenceTypeId typeId, Tvl.Java.DebugInterface.Types.ClassObjectId classObject) {
            return base.Channel.GetReflectedType(out typeTag, out typeId, classObject);
        }
    }
}
